name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: python3 version
      run: python3 --version
    - name: where am I?
      run: ls -al
    - name: where python?
      run: ls /usr/bin/python*
