name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: what to point at?
      run: ls -al /opt/hostedtoolcache/Python/3.7.4
