name:

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          version: 3.7.4
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: black
        run: black . --check
      - name: flake8
        run: flake8
      - name: Run all tests
        run: pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
          flags: alltests
